### PR TITLE
dyn api version 3.7.0

### PR DESCRIPTION
**Pull request by sbfaulkner**
we need to bump to version 3.7.0 of the api in order to manage ALIAS records

### CODE REVIEW

**Review by plribeiro3000 — COMMENTED** [review]
I'm sorry for this (kind of dumby question) but isn't this going to break any feature we already have?

**Comment by sbfaulkner** [comment]
I'll see if I can get more info about the changes in the dynect api but don't think a minor version bump should break anything

**Comment by plribeiro3000** [comment]
I agree. I wouldn't expect it to break but just for the sake of it maybe is a good idea to confirm. =)

**Comment by sbfaulkner** [comment]
After a lot of digging on the dyn site, I finally found this... https://manage.dynect.net/help/changelog.html

I don't see anything that should be a breaking change.

Here's the extracted API changes for reference.

**Version 3.7.0**
- New ACL has been added for API access. When utilized, the WEB and API ACLs are managed separately.

**Version 3.6.11**
- Task IDs are now included in most API responses where a task is used to track progress.
- New task-related calls are available for viewing their status and canceling long-running or doomed tasks.

**Version 3.6.10**
- Failover recovery via REST API.

**Version 3.6.6**
- API calls for DSFRecordSet now all use "dsf_monitor_id" instead of "monitor_id"

**Version 3.6.5**
- Added CDS and CDNSKEY record type support.

**Version 3.6.2 ?**
- Detail flag on a REST API call returns proper HTTP status code.

**API version 3.6.0**
- Traffic Director API calls properly honor attached node limits
- TSIG key calls now require the 'algorithm' field
- Nodes may now be detached from a Traffic Director service through the API

**API version 3.5.6**
- No changes to API behavior from the previous version.

**API version 3.5.5**
- SOA Serial Style may now be modified via the UI and API

**Comment by sbfaulkner** [comment]
related question @plribeiro3000 ...

in order to support passing a version into the provider (without getting the warning `[fog][WARNING] Unrecognized arguments: version`) should :version be added here... https://github.com/fog/fog-dynect/blob/master/lib/fog/dynect/dns.rb#L5 ?

**Comment by plribeiro3000** [comment]
Again. Thanks for your hard work on this @sbfaulkner. 👍

**Comment by sbfaulkner** [comment]
thanks @plribeiro3000 any chance we can get a fog-dynect version bump and ship to rubygems ?

**Comment by plribeiro3000** [comment]
Sure. Let me do this real quick.

**Comment by plribeiro3000** [comment]
Hmmm. Unfortunately, i don't have access of `fog-dynect` on rubygem. Let me see about that with the rest of the crew.

**Comment by plribeiro3000** [comment]
Here you go. version `0.1.0`.
It ships other changes as well. =)

**Pull request merged**
